/* D3DCAPS - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package jagdx;

public class D3DCAPS {
    public int PresentationIntervals;
    public int MaxVertexIndex;
    public int LineCaps;
    public int DevCaps;
    public int Caps3;
    public int MaxStreamStride;
    public float MaxPointSize;
    public int MaxVolumeExtent;
    public int MaxTextureBlendStages;
    public int CubeTextureFilterCaps;
    public int MaxVertexShaderConst;
    public int MaxSimultaneousTextures;
    public int PixelShaderVersion;
    public int TextureCaps;
    public int Caps2;
    public int PrimitiveMiscCaps;
    public int RasterCaps;
    public int AdapterOrdinal;
    public int AlphaCmpCaps;
    public int VolumeTextureAddressCaps;
    public int MaxStreams;
    public int CursorCaps;
    public float PixelShader1xMaxValue;
    public int SrcBlendCaps;
    public int VertexShaderVersion;
    public D3DVSHADERCAPS2_0 VS20Caps = new D3DVSHADERCAPS2_0();
    public float MaxVertexW;
    public int ShadeCaps;
    public int StencilCaps;
    public int MaxTextureAspectRatio;
    public int FVFCaps;
    public float ExtentsAdjust;
    public int MaxAnisotropy;
    public float GuardBandRight;
    public float GuardBandBottom;
    public int ZCmpCaps;
    public int DestBlendCaps;
    public int MaxVertexBlendMatrixIndex;
    public int DeviceType;
    public int MaxVertexBlendMatrices;
    public int MaxPrimitiveCount;
    public int Caps;
    public int TextureOpCaps;
    public int TextureAddressCaps;
    public float GuardBandTop;
    public float GuardBandLeft;
    public int MaxTextureWidth;
    public int TextureFilterCaps;
    public int MaxTextureHeight;
    public int VolumeTextureFilterCaps;
    public int MaxTextureRepeat;
    public int VertexProcessingCaps;
    public int MaxUserClipPlanes;
    public int MaxActiveLights;
    public D3DPSHADERCAPS2_0 PS20Caps = new D3DPSHADERCAPS2_0();
    public int MasterAdapterOrdinal;
    public int NumSimultaneousRTs;
    public int MaxPShaderInstructionsExecuted;
    public int StretchRectFilterCaps;
    public int MaxVShaderInstructionsExecuted;
    public int VertexTextureFilterCaps;
    public int DevCaps2;
    public int NumberOfAdaptersInGroup;
    public int MaxVertexShader30InstructionSlots;
    public int AdapterOrdinalInGroup;
    public int MaxPixelShader30InstructionSlots;
    public int DeclTypes;
}
